import { SoundFont, Synthesizer } from "https://cdn.jsdelivr.net/npm/spessasynth_lib@3.20.0/+esm";

const $ = id => document.getElementById(id);
const log = m => $("log").textContent = m;
let sfData = null, synth = null, selectedPreset = 0, chart = null, songName = "ai-madness";

const keySaved = localStorage.getItem("ai-fnf-api-key");
if (keySaved) $("apiKey").value = keySaved;

for(let n=48;n<=84;n++) {
  const o=document.createElement("option"); o.value=n; o.textContent=`MIDI ${n}`; $("previewNote").appendChild(o);
}

$("saveKey").onclick=()=>{
  localStorage.setItem("ai-fnf-api-key",$("apiKey").value.trim());
  $("aiStatus").textContent="Saved locally.";
};

$("testKey").onclick=async()=>{
  const key=$("apiKey").value.trim();
  if(!key){$("aiStatus").textContent="Enter an API key first.";return}
  $("aiStatus").textContent="Testing...";
  try{
    const r=await fetch("https://api.openai.com/v1/models",{headers:{Authorization:`Bearer ${key}`}});
    $("aiStatus").textContent=r.ok?"Connection OK.":"Connection failed: HTTP "+r.status;
  }catch(e){$("aiStatus").textContent="Connection error: "+e.message}
};

$("sf2").onchange=async e=>{
  const f=e.target.files[0]; if(!f)return;
  $("sfStatus").textContent="Loading "+f.name+"...";
  try{
    sfData=await f.arrayBuffer();
    const sf=await SoundFont.fromArrayBuffer(sfData);
    $("preset").innerHTML="";
    sf.presets.forEach((p,i)=>{
      const o=document.createElement("option");
      o.value=i;o.textContent=`${i}: ${p.name||"Preset"}`;
      $("preset").appendChild(o);
    });
    $("sfStatus").textContent=`Loaded ${f.name} • ${sf.presets.length} presets`;
    synth = new Synthesizer({soundfont:sf});
  }catch(e){$("sfStatus").textContent="SF2 load failed: "+e.message}
};

$("preset").onchange=e=>selectedPreset=+e.target.value||0;

$("testNote").onclick=async()=>{
  if(!synth){$("sfStatus").textContent="Load an SF2 first.";return}
  const note=+$("previewNote").value;
  try{
    synth.programChange(0,selectedPreset);
    synth.noteOn(0,note,110);
    setTimeout(()=>synth.noteOff(0,note),500);
    $("sfStatus").textContent="Playing preview note.";
  }catch(e){$("sfStatus").textContent="Preview failed: "+e.message}
};

function slug(s){return s.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"song"}
function makeChart(){
  const bpm=+$("bpm").value||180, len=+$("length").value||90;
  const step=60000/bpm/2, notes=[];
  const total=Math.floor(len*1000/step);
  for(let i=0;i<total;i++){
    if(i<16) continue;
    const bar=i%16;
    if(bar===0||bar===4||bar===8||bar===12) notes.push([i*step,0,0]);
    if(bar===2||bar===6||bar===10||bar===14) notes.push([i*step,1,0]);
    if(i%8===7) notes.push([i*step,2,0]);
  }
  return {
    song:{
      song:songName,
      notes:notes.map(n=>({sectionNotes:[[n[0],n[1],0]],lengthInSteps:16})).slice(0,Math.max(1,Math.floor(notes.length/1))),
      bpm,
      needsVoices:false,
      speed:1,
      player1:$("player").value.trim()||"bf",
      player2:$("opponent").value.trim()||"dad",
      gfVersion:"gf",
      stage:$("stage").value.trim()||"stage",
      validScore:true
    }
  };
}

async function aiGenerate(){
  const key=$("apiKey").value.trim();
  if(!key) return null;
  const prompt=`Generate structured FNF chart planning data for this request. Return JSON only with arrays of note events. Request: ${$("prompt").value}. BPM: ${$("bpm").value}. Length: ${$("length").value} seconds.`;
  const r=await fetch("https://api.openai.com/v1/responses",{
    method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${key}`},
    body:JSON.stringify({model:"gpt-4.1-mini",input:prompt})
  });
  if(!r.ok) throw new Error(`AI HTTP ${r.status}`);
  const data=await r.json();
  return data.output_text||"";
}

$("generate").onclick=async()=>{
  songName=slug($("songName").value);
  log("Generating chart...");
  try{
    let aiText=null;
    if($("apiKey").value.trim()){
      try{aiText=await aiGenerate();}catch(e){log("AI request failed; using local generator. "+e.message)}
    }
    chart=makeChart();
    if(aiText) chart.song.generatedByAI=true;
    $("export").disabled=false;$("previewJson").disabled=false;
    log(`Generated ${songName} • ${chart.song.notes.length} chart sections • ${$("bpm").value} BPM`);
  }catch(e){log("Generation failed: "+e.message)}
};

$("previewJson").onclick=()=>{
  if(chart) log(JSON.stringify(chart,null,2));
};

$("export").onclick=async()=>{
  if(!chart)return;
  const zip=new JSZip(), mod=slug($("modName").value)||"ai-mod";
  const s=songName;
  const folder=`mods/${mod}`;
  zip.file(`${folder}/data/${s}/${s}-${$("difficulty").value.toLowerCase()}.json`,JSON.stringify(chart,null,2));
  zip.file(`${folder}/songs/${s}/README.txt`,
`Generated by AI FNF Mod Maker.
Song: ${s}
BPM: ${chart.song.bpm}
Instrumental audio should be placed here as Inst.ogg.
`);
  zip.file(`${folder}/README.txt`,`Psych Engine 1.0.4 generated mod\\n\\nSong: ${s}\\n`);
  if(sfData) zip.file(`${folder}/soundfonts/imported.sf2`,sfData);
  const blob=await zip.generateAsync({type:"blob"});
  const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${mod}.zip`;a.click();
  setTimeout(()=>URL.revokeObjectURL(a.href),1000);
  log("ZIP exported.");
};
